#!/usr/bin/python

import os
fdir = os.path.dirname(os.path.realpath(__file__))

import shutil

nginx_raw = open(os.path.join(fdir, '..', 'assets', 'nginx.conf')).read()

if "DOMAIN_NAME" in os.environ:
    nginx_raw = nginx_raw.replace("${DOMAIN_NAME}", os.environ["DOMAIN_NAME"])

open('/etc/nginx/nginx.conf', 'w').write(nginx_raw)

shutil.rmtree("/etc/nginx/sites-available")
shutil.rmtree("/etc/nginx/sites-enabled")
