#!/bin/bash

if [ "$INTERNAL_MONGO" == "yes" ]; then
    service mongodb start
fi
chmod +x /root # for nginx
chmod +x /root/certs
chmod +x /root/data
/root/venue/scripts/docker/generate-cert
/root/venue/scripts/docker/configure-nginx
/usr/sbin/nginx
cd /root/venue
# gulp serve:dist
tail -f /dev/null
