#!/bin/bash

if [ "$INTERNAL_MONGO" == "yes" ]; then
    service mongodb start
else
    service mongodb stop
fi
/root/venue/scripts/docker/generate-cert
/root/venue/scripts/docker/configure-nginx
/usr/sbin/nginx
cd /root/venue
# grunt serve:dist
tail -f /dev/null
