#!/bin/bash

if [ ! -f /root/venue/server/config/local.env.js ]; then
    cp /root/venue/server/config/local.env.sample.js /root/venue/server/config/local.env.js
fi

vim /root/venue/server/config/local.env.js
