#!/bin/bash

. /root/.bashrc
. ~/.nvm/nvm.sh
service nginx stop
nginx
cd /root/venue

if [ "$PRODUCTION_RUN" == "yes" ]; then
    echo "SERVING PRODUCTION" | tee /root/venueprod.log
    gulp serve:dist | tee /root/venueprod.log
else
    echo "SERVING HEADLESS" | tee /root/venue.log
    grunt --no-color serve:headless | tee /root/venue.log
fi
