#!/bin/bash

. /root/.bashrc
. ~/.nvm/nvm.sh
service nginx stop
nginx
cd /root/venue

if [ "$PRODUCTION_RUN" == "yes" ]; then
    echo "SERVING PRODUCTION" >> /root/venue.log
    grunt serve:dist >> /root/venue.log
else
    echo "SERVING HEADLESS" >> /root/venue.log
    grunt serve:headless >> /root/venue.log
fi
