#!/bin/bash

# Simple docker run
# docker run -p 443:443 -p 9000:9000 -p 80:80 --name venue -dit rcos/venue

# See venuestart-dev for some example environment variables

# This will pull from the server's environment variables
docker run \
-e DOMAIN \
-e DOMAIN_NAME \
-e VENUE_SECRET \
-e CAS_SERVER_URL \
-e CAS_VERSION \
-e SCHOOL_EMAIL_SUFFIX \
-e EMAIL_SERVICE \
-e SENDGRID_KEY \
-e SMTP_LOGIN \
-e EMAIL_SERVICE \
-e SERVER_EMAIL \
-e SMTP_PASSWORD \
-e INTERNAL_MONGO \
-e PRODUCTION_RUN \
-e LOCAL_LOGIN \
-e DEBUG_LOGIN \
-P \
--net="host" \
--name venue -dit rcos/venue
